### ISSUE TITLE
COMiniSat link is dead

### ISSUE THREAD

**Issue by raki123** [marekpiotrow/UWrMaxSat#7]
Hi,
thank you for the solver!
I have been using it for a while but since recently the link the COMiniSat solver seems to not work anymore.
(This one https://baldur.iti.kit.edu/sat-competition-2016/solvers/main/COMiniSatPSChandrasekharDRUP.zip)
I am using Cadical instead now but I thought you might want to know.
Best wishes,
Rafael

**Comment by marekpiotrow** [comment]
Hi,

I did not know, so thanks.

I have changed the instruction in README.md to use https://github.com/marekpiotrow/cominisatps instead of the dead link and updated both repositories to the modified README. In particular, the patch to the original COMiniSatPS is already applied to the cominisatps project.

Marek

**Comment by raki123** [comment]
Great thanks! Everything works flawlessly now!
